"""Cut the Garden Shop's three pictures into components/gardenShopSheet.ts

    python3 scripts/forage_art/cut_garden_shop.py

Sources are in art/garden-shop/ (they came in through Plate Drop):
  items.jpg  32 shop items on magenta, ruled. Rows 1-3 are a true 8-across grid;
             row 4 is NOT: the generator packed several items into a few wide
             cells (and drew the rain gun's spray gun on its own), so row 4 is cut
             into blobs, left to right, and the loose gun is dropped.
  ui.jpg     4x2: the shopkeeper (on her own green ground, not keyed), the shop
             sign, the propagator, the vent opener, then four tab icons.
  scene.jpg  the shop interior, the header banner.

Each sprite is keyed, cropped to itself and fitted to a square at SIDE px (drawn
smaller with image-rendering: pixelated), WebP. The ruled lines are dark purple
and are keyed along with the magenta.
"""
import os, io, base64
import numpy as np
from PIL import Image
from cut_sheet import key, blobs

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(REPO, 'art', 'garden-shop')
SIDE = 96
INSET = 7

# Row 4 blobs, left to right: nematodes, ladybird tube, lacewing card, encarsia cards,
# Bt, the rain gun's reel, the rotavator, the tractor.
ROW4 = [24, 25, 26, 27, 28, 29, 30, 31]
# The rain gun's spray gun was drawn loose, and its hose touches the rotavator, so the
# two are one blob. The gun is erased first (sheet pixels: left of x948, and the
# barrel's tip up to x1010 above y625).


def keyed(im: Image.Image) -> np.ndarray:
    a = key(im)
    r, g, b = (a[..., i].astype(int) for i in range(3))
    rule = (r - g > 40) & (b - g > 40) & (np.abs(r - b) < 70) & (r < 170)
    a[..., 3] = np.where(rule, 0, a[..., 3])
    return a


def fit(rgba: Image.Image, side=SIDE) -> Image.Image:
    box = rgba.getchannel('A').getbbox()
    if box: rgba = rgba.crop(box)
    k = min(1.0, side / max(rgba.size))
    if k < 1:
        rgba = rgba.resize((max(1, round(rgba.width * k)), max(1, round(rgba.height * k))), Image.LANCZOS)
        rgba.putalpha(rgba.getchannel('A').point(lambda v: 255 if v > 110 else 0))
    sq = Image.new('RGBA', (side, side), (0, 0, 0, 0))
    sq.paste(rgba, ((side - rgba.width) // 2, (side - rgba.height) // 2), rgba)
    return sq


def uri(im: Image.Image, **kw) -> str:
    buf = io.BytesIO(); im.save(buf, 'WEBP', **kw)
    return 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode()


def grid(a: np.ndarray, cols: int, rows: int, r: int, c: int) -> Image.Image:
    h, w = a.shape[:2]
    return Image.fromarray(a[h * r // rows + INSET:h * (r + 1) // rows - INSET, w * c // cols + INSET:w * (c + 1) // cols - INSET])


def items():
    src = Image.open(os.path.join(SRC, 'items.jpg')).convert('RGB')
    a = keyed(src)
    out = {}
    for r in range(3):
        for c in range(8):
            out[r * 8 + c] = fit(grid(a, 8, 4, r, c))
    h, w = a.shape[:2]
    y0 = h * 3 // 4 + INSET
    gun = np.zeros(a.shape[:2], bool)
    gun[y0:, 870:948] = True
    gun[y0:625, 948:1010] = True
    a[..., 3] = np.where(gun, 0, a[..., 3])
    band = a[y0:h - INSET]
    small = band[::2, ::2, 3] > 0
    # a sliver of ruled line survives at the sheet's edge: anything under 6 px wide is not an item
    boxes = [b for b in blobs(small, merge=3) if (b[2] - b[0]) * (b[3] - b[1]) >= 60 and b[2] - b[0] >= 3]
    boxes.sort(key=lambda b: b[0])
    assert len(boxes) == len(ROW4), f'row 4 has {len(boxes)} blobs, expected {len(ROW4)}: {boxes}'
    for b, cell in zip(boxes, ROW4):
        out[cell] = fit(Image.fromarray(band[b[1] * 2:b[3] * 2, b[0] * 2:b[2] * 2]))
    return [out[i] for i in range(32)]


def ui():
    src = Image.open(os.path.join(SRC, 'ui.jpg')).convert('RGB')
    a = keyed(src)
    cells = []
    for i in range(8):
        r, c = divmod(i, 4)
        if i == 0:
            # the shopkeeper keeps her painted ground: a portrait for a round crop
            h, w = a.shape[:2]
            im = src.crop((w * c // 4 + INSET, h * r // 2 + INSET, w * (c + 1) // 4 - INSET, h * (r + 1) // 2 - INSET))
            s = min(im.size); im = im.crop(((im.width - s) // 2, 0, (im.width - s) // 2 + s, s)).resize((SIDE, SIDE), Image.LANCZOS)
            cells.append(im.convert('RGBA'))
        else:
            cells.append(fit(grid(a, 4, 2, r, c)))
    return cells


def main():
    it, u = items(), ui()
    scene = Image.open(os.path.join(SRC, 'scene.jpg')).convert('RGB').resize((960, 536), Image.LANCZOS)
    total = 0
    out = ['/* Generated by scripts/forage_art/cut_garden_shop.py from art/garden-shop/. Do not edit. */',
           '/** The Garden Shop\'s pictures: 32 items and 8 interface cells, each a square of ' + str(SIDE) + ' px, and the shop interior. */']
    def arr(name, ims):
        nonlocal total
        us = [uri(i, quality=88, alpha_quality=90) for i in ims]
        total += sum(len(x) for x in us)
        out.append(f'export const {name}: string[] = [')
        out.extend(f"  '{x}'," for x in us)
        out.append('];')
    arr('GS_ITEMS', it)
    arr('GS_UI', u)
    s = uri(scene, quality=80); total += len(s)
    out.append(f"export const GS_SCENE = '{s}';")
    with open(os.path.join(REPO, 'components', 'gardenShopSheet.ts'), 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(len(it), 'items', len(u), 'ui', total // 1024, 'KB')


if __name__ == '__main__':
    main()
