"""Cut the owner's farm tool and farm unit sheets into icons: components/farmIconSheet.ts

    python3 scripts/forage_art/cut_icons.py [folder of generated images]

Cells are named by row.column as rows_of numbers them; check a new sheet as an
indexed contact strip before trusting the numbering (the tool sheet's spore print
is two blobs, card and glass, so its row has nine cells).
"""
import os, sys, io, base64
from PIL import Image
import numpy as np
from cut_sheet import cut, rows_of, key
from snap_plates import snap

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Downloads')
SHEETS = {
    'tools': 'Gemini_Generated_Image_jd9xcjjd9xcjjd9x.jpeg',
    'units': 'Gemini_Generated_Image_lec255lec255lec2.jpeg',
    'hens':  'Gemini_Generated_Image_r02y90r02y90r02y.jpeg',
}
# The kit sheet is a ruled 3x2 grid: the black rules would join every tool into one
# blob, so they are erased and the sheet is cut on its grid instead (cells 0.0 to 1.2).
KIT_BOX = 50
KIT_SHEET = ('kit', 'Gemini_Generated_Image_7ab3xh7ab3xh7ab3.jpeg', 3, 2)
# Hens: four breeds as rows (brown, white, black, speckled), seven frames each (stand,
# walk x3, peck, scratch, sit), all facing right. Painted about 58 px tall, three times the
# run's scale, so they are shrunk here by one factor for every frame of a breed.
HEN_BREEDS = ['brown', 'white', 'black', 'speckled']
HEN_TALL = 19
ICONS = {
    # the farm kit, by FARM_TOOLS id
    'hose': ('tools', '0.1'), 'drip': ('tools', '0.2'), 'stirrup_hoe': ('tools', '0.4'),
    'netting': ('tools', '1.3'), 'fleece': ('tools', '1.4'), 'sticky_traps': ('tools', '1.6'),
    'long_pruner': ('tools', '1.1'), 'ladder': ('tools', '1.2'), 'extractor': ('tools', '2.4'),
    'auto_door': ('tools', '2.6'),
    # things on the panels
    'egg_basket': ('tools', '2.7'), 'feeder': ('tools', '1.5'), 'smoker': ('tools', '2.0'),
    'hive': ('units', '1.0'), 'hive_busy': ('units', '1.4'),
    'worm_tower': ('units', '0.0'), 'worm_tray': ('units', '2.0'),
    'fly_bin': ('units', '3.0'), 'fly_bin_busy': ('units', '3.3'), 'fly_bin_full': ('units', '3.6'),
    'sack_frass': ('units', '4.0'), 'sack_castings': ('units', '4.4'),
    # the rest of the kit, off the ruled sheet
    'sprayer': ('kit', '0.0'), 'traps': ('kit', '0.1'), 'scarecrow': ('kit', '0.2'),
    'electric_fence': ('kit', '1.0'), 'seed_drill': ('kit', '1.1'), 'scythe': ('kit', '1.2'),
}


def grid_cells(path, cols, rows):
    """Snap, key, erase the dark rules, and crop each grid cell to what is in it."""
    a = key(snap(path, palette=False).convert('RGB'))
    dark = a[..., :3].sum(axis=2) < 150
    for x in np.where(dark.mean(axis=0) > 0.6)[0]: a[:, max(0, x - 1):x + 2, 3] = 0
    for y in np.where(dark.mean(axis=1) > 0.6)[0]: a[max(0, y - 1):y + 2, :, 3] = 0
    a[:2, :, 3] = 0; a[-2:, :, 3] = 0; a[:, :2, 3] = 0; a[:, -2:, 3] = 0
    im = Image.fromarray(a)
    h, w = a.shape[:2]
    out = {}
    for r in range(rows):
        for c in range(cols):
            cell = im.crop((w * c // cols, h * r // rows, w * (c + 1) // cols, h * (r + 1) // rows))
            cell = cell.crop(cell.getchannel('A').getbbox())
            # This sheet paints each tool three times the size of the first tool sheet's,
            # so it is fitted to the same 50 px box, alpha cut hard so the edge stays a pixel edge.
            k = min(1, KIT_BOX / max(cell.size))
            if k < 1:
                cell = cell.resize((max(1, round(cell.width * k)), max(1, round(cell.height * k))), Image.LANCZOS)
                cell.putalpha(cell.getchannel('A').point(lambda v: 255 if v > 110 else 0))
            out[f'{r}.{c}'] = cell
    return out
# The 3lgfas sheet (press, bread maker, trays, carboy, clock, mister, barrel, paddle) is
# smooth illustration on a ruled grid, not pixel art, and has no farm tool on it: not used.

def main():
    cells = {}
    for name, fn in SHEETS.items():
        rgba, boxes = cut(os.path.join(SRC, fn))
        im = rgba if isinstance(rgba, Image.Image) else Image.fromarray(rgba)
        for ri, row in enumerate(rows_of(boxes)):
            for ci, b in enumerate(row):
                cells[(name, f'{ri}.{ci}')] = im.crop(tuple(b))
    name, fn, cols, rows = KIT_SHEET
    for k, c in grid_cells(os.path.join(SRC, fn), cols, rows).items():
        cells[(name, k)] = c
    out = ['/* Generated by scripts/forage_art/cut_icons.py from the owner\'s farm tool and unit sheets. Do not edit. */',
           'export const FARM_ICONS: Record<string, { src: string; w: number; h: number }> = {']
    total = 0
    for key, (sheet, cell) in ICONS.items():
        c = cells[(sheet, cell)]
        buf = io.BytesIO(); c.save(buf, 'WEBP', lossless=True)
        b = buf.getvalue(); total += len(b)
        out.append(f"  {key}: {{ src: 'data:image/webp;base64,{base64.b64encode(b).decode()}', w: {c.width}, h: {c.height} }},")
    out.append('};')
    # the hens, pre-shrunk: LANCZOS, then the alpha cut hard so the edge stays a pixel edge
    out.append('/** Hen frames by breed: stand, walk x3, peck, scratch, sit; facing right. */')
    out.append('export const HEN_FRAMES: Record<string, { src: string; w: number; h: number }[]> = {')
    for ri, breed in enumerate(HEN_BREEDS):
        row = [cells[('hens', f'{ri}.{ci}')] for ci in range(7)]
        k = HEN_TALL / row[0].height
        frames = []
        for c in row:
            w, h = max(1, round(c.width * k)), max(1, round(c.height * k))
            sm = c.resize((w, h), Image.LANCZOS)
            a = sm.getchannel('A').point(lambda v: 255 if v > 110 else 0)
            sm.putalpha(a)
            buf = io.BytesIO(); sm.save(buf, 'WEBP', lossless=True)
            b = buf.getvalue(); total += len(b)
            frames.append(f"{{ src: 'data:image/webp;base64,{base64.b64encode(b).decode()}', w: {w}, h: {h} }}")
        out.append(f"  {breed}: [{', '.join(frames)}],")
    out.append('};')
    with open(os.path.join(REPO, 'components', 'farmIconSheet.ts'), 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(len(ICONS), 'icons', total // 1024, 'KB')

if __name__ == '__main__':
    main()
