"""Cut the owner's farm tool and farm unit sheets into icons: components/farmIconSheet.ts

    python3 scripts/forage_art/cut_icons.py [folder of generated images]

Cells are named by row.column as rows_of numbers them; check a new sheet as an
indexed contact strip before trusting the numbering (the tool sheet's spore print
is two blobs, card and glass, so its row has nine cells).
"""
import os, sys, io, base64
from PIL import Image
from cut_sheet import cut, rows_of

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Downloads')
SHEETS = {
    'tools': 'Gemini_Generated_Image_jd9xcjjd9xcjjd9x.jpeg',
    'units': 'Gemini_Generated_Image_lec255lec255lec2.jpeg',
}
ICONS = {
    # the farm kit, by FARM_TOOLS id
    'hose': ('tools', '0.1'), 'drip': ('tools', '0.2'), 'stirrup_hoe': ('tools', '0.4'),
    'netting': ('tools', '1.3'), 'fleece': ('tools', '1.4'), 'sticky_traps': ('tools', '1.6'),
    'long_pruner': ('tools', '1.1'), 'ladder': ('tools', '1.2'), 'extractor': ('tools', '2.4'),
    'auto_door': ('tools', '2.6'),
    # things on the panels
    'egg_basket': ('tools', '2.7'), 'feeder': ('tools', '1.5'), 'smoker': ('tools', '2.0'),
    'hive': ('units', '1.0'), 'hive_busy': ('units', '1.4'),
    'worm_tower': ('units', '0.0'), 'worm_tray': ('units', '2.0'),
    'fly_bin': ('units', '3.0'), 'fly_bin_busy': ('units', '3.3'), 'fly_bin_full': ('units', '3.6'),
    'sack_frass': ('units', '4.0'), 'sack_castings': ('units', '4.4'),
}

def main():
    cells = {}
    for name, fn in SHEETS.items():
        rgba, boxes = cut(os.path.join(SRC, fn))
        im = rgba if isinstance(rgba, Image.Image) else Image.fromarray(rgba)
        for ri, row in enumerate(rows_of(boxes)):
            for ci, b in enumerate(row):
                cells[(name, f'{ri}.{ci}')] = im.crop(tuple(b))
    out = ['/* Generated by scripts/forage_art/cut_icons.py from the owner\'s farm tool and unit sheets. Do not edit. */',
           'export const FARM_ICONS: Record<string, { src: string; w: number; h: number }> = {']
    total = 0
    for key, (sheet, cell) in ICONS.items():
        c = cells[(sheet, cell)]
        buf = io.BytesIO(); c.save(buf, 'WEBP', lossless=True)
        b = buf.getvalue(); total += len(b)
        out.append(f"  {key}: {{ src: 'data:image/webp;base64,{base64.b64encode(b).decode()}', w: {c.width}, h: {c.height} }},")
    out.append('};')
    with open(os.path.join(REPO, 'components', 'farmIconSheet.ts'), 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(len(ICONS), 'icons', total // 1024, 'KB')

if __name__ == '__main__':
    main()
