"""Cut the owner's farm-hand portraits into components/farmFaceSheet.ts

    python3 scripts/forage_art/cut_faces.py [folder of generated images]

The sheet is a 6x3 grid on magenta (the third row empty): two people per farm role,
in the order below. Each face is keyed, bottom-aligned into a square and saved at
the crew portraits' 160 px, like the koji keepers' faces.
"""
import os, sys, io, base64
import numpy as np
from PIL import Image
from cut_sheet import key

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Downloads')
SHEET = 'Gemini_Generated_Image_8zo50a8zo50a8zo5.jpeg'
COLS, ROWS = 6, 3
ORDER = [['gardener', 'gardener', 'orchardist', 'orchardist', 'beekeeper', 'beekeeper'],
         ['poultry', 'poultry', 'soil_tech', 'soil_tech', 'forager', 'forager']]
CELL = 160

def main():
    src = Image.open(os.path.join(SRC, SHEET)).convert('RGB')
    cw, ch = src.width / COLS, src.height / ROWS
    faces = {}
    total = 0
    for r, row in enumerate(ORDER):
        for c, role in enumerate(row):
            cell = src.crop((int(c * cw) + 3, int(r * ch) + 3, int((c + 1) * cw) - 3, int((r + 1) * ch) - 3))
            rgba = Image.fromarray(key(cell))
            # A veil is mesh: the magenta behind it shows through as lilac. Pale pixels
            # carrying that tint are set to their own grey.
            a = np.asarray(rgba).astype(int)
            r_, g_, b_ = a[..., 0], a[..., 1], a[..., 2]
            lilac = (r_ - g_ > 18) & (b_ - g_ > 18) & ((r_ + g_ + b_) / 3 > 110)
            grey = ((r_ + b_) // 2 + g_ * 2) // 3
            for k_ in range(3):
                a[..., k_] = np.where(lilac, grey, a[..., k_])
            rgba = Image.fromarray(a.astype(np.uint8))
            box = rgba.getchannel('A').getbbox()
            rgba = rgba.crop(box)
            side = max(rgba.width, rgba.height)
            sq = Image.new('RGBA', (side, side), (0, 0, 0, 0))
            sq.paste(rgba, ((side - rgba.width) // 2, side - rgba.height), rgba)
            sq = sq.resize((CELL, CELL), Image.LANCZOS)
            buf = io.BytesIO(); sq.save(buf, 'WEBP', quality=86)
            b = buf.getvalue(); total += len(b)
            faces.setdefault(role, []).append('data:image/webp;base64,' + base64.b64encode(b).decode())
    out = ['/**', ' * THE FARM HANDS\' FACES.', ' *',
           ' * Two painted people for each farm role, in working clothes. Generated by',
           f' * scripts/forage_art/cut_faces.py; chosen by hashing the member\'s id. {total // 1024} kB.', ' */',
           'export const FARM_FACES: Record<string, string[]> = {']
    for role, fs in faces.items():
        out.append(f'  {role}: [' + ', '.join(f"'{f}'" for f in fs) + '],')
    out.append('};')
    with open(os.path.join(REPO, 'components', 'farmFaceSheet.ts'), 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(sum(len(v) for v in faces.values()), 'faces', total // 1024, 'KB')

if __name__ == '__main__':
    main()
