"""Cut the owner's townsfolk sheet into components/townFaceSheet.ts

    python3 scripts/forage_art/cut_town.py [folder of generated images]

A 4x3 grid on magenta with darker ruled lines between the cells. Each person is
keyed, bottom-aligned into a square and saved at 160 px, like the farm hands.
The order is the sheet's, row by row; constants.town.ts names who is who.
"""
import os, sys, io, base64
from PIL import Image
from cut_sheet import key

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/Downloads')
SHEET = 'Gemini_Generated_Image_fxom2fxom2fxom2f.jpeg'
COLS, ROWS = 4, 3
ORDER = ['smith', 'spinner', 'crier', 'herbalist',
         'captain', 'cooper', 'monk', 'minstrel',
         'farmhand', 'innkeeper', 'mason', 'elder']
CELL = 160
INSET = 8   # clear of the ruled lines


def main():
    src = Image.open(os.path.join(SRC, SHEET)).convert('RGB')
    cw, ch = src.width / COLS, src.height / ROWS
    faces, total = {}, 0
    for i, who in enumerate(ORDER):
        r, c = divmod(i, COLS)
        cell = src.crop((int(c * cw) + INSET, int(r * ch) + INSET, int((c + 1) * cw) - INSET, int((r + 1) * ch) - INSET))
        rgba = Image.fromarray(key(cell))
        rgba = rgba.crop(rgba.getchannel('A').getbbox())
        side = max(rgba.width, rgba.height)
        sq = Image.new('RGBA', (side, side), (0, 0, 0, 0))
        sq.paste(rgba, ((side - rgba.width) // 2, side - rgba.height), rgba)
        sq = sq.resize((CELL, CELL), Image.LANCZOS)
        buf = io.BytesIO(); sq.save(buf, 'WEBP', quality=86)
        b = buf.getvalue(); total += len(b)
        faces[who] = 'data:image/webp;base64,' + base64.b64encode(b).decode()
    out = ['/**', ' * THE TOWNSFOLK\'S FACES.', ' *',
           ' * Twelve painted people from the market town. Generated by',
           f' * scripts/forage_art/cut_town.py. {total // 1024} kB.', ' */',
           'export const TOWN_FACES: Record<string, string> = {']
    for who, f in faces.items():
        out.append(f"  {who}: '{f}',")
    out.append('};')
    with open(os.path.join(REPO, 'components', 'townFaceSheet.ts'), 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(len(faces), 'faces', total // 1024, 'KB')


if __name__ == '__main__':
    main()
